services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./PostgresDB/init:/docker-entrypoint-initdb.d
      # - ./PostgresDB/postgresql.conf:/etc/postgresql/postgresql.conf
      # - ./PostgresDB/pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./UserService
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/userservice
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./UserService:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: